### ISSUE TITLE
Layout gets less tall when validate() returns true

### ISSUE THREAD

**Issue by tdekoning** [julianraj/ValidatedInputTextLayout#6]
In our case, we want to always have the same height in our textinputlayouts, so we dont get a jumpy form. We can achieve this by calling `setErrorEnabled(true);` upon creation, this will reserve the space required for the error message, but will not actually show the message yet.
But when our form fields validate correctly, the `ValidatedTextInputLayout` calls `setErrorEnabled(false);`, removing the additional space that was already shown.

For now, i can resolve the issue for myself by extending the `ValidatedTextInputLayout` and overriding the `validate` method like this:
```kotlin
override fun validate() : Boolean {
        val valid = super.validate()
        // For now, this is required to prevent jumpy behaviour.
        isErrorEnabled = true
        return valid
}
```

But a more permanent fix would be awesome

**Comment by julianmanandhar** [comment]
thanks for the feedback @tdekoning 
will add the changes in the next release..  possibly within few days. :smile:

**Comment by tdekoning** [comment]
Thank you!

**Comment by julianmanandhar** [comment]
@tdekoning  v0.2.0 now available
Shouldn't be jumpy now.. :wink: 

However Just in case someones wants to remove the error space after validation (Such as me :grin:)  they can set `app:errorAlwaysEnabled="false"` in xml or `mInput.setErrorAlwaysEnabled(false);` in java code.

by default its `true`..

**Comment by tdekoning** [comment]
That is a fine solution, thank you for the quick update!
